/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'root': RouteRecordInfo<'root', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'history-page': RouteRecordInfo<'history-page', '/history-page', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'market-page': RouteRecordInfo<'market-page', '/market-page', Record<never, never>, Record<never, never>>,
    'second-page': RouteRecordInfo<'second-page', '/second-page', Record<never, never>, Record<never, never>>,
    'third-page': RouteRecordInfo<'third-page', '/third-page', Record<never, never>, Record<never, never>>,
    'token-api-tester': RouteRecordInfo<'token-api-tester', '/TokenApiTester', Record<never, never>, Record<never, never>>,
    'token-historical-page': RouteRecordInfo<'token-historical-page', '/TokenHistoricalPage', Record<never, never>, Record<never, never>>,
    'token-market-page': RouteRecordInfo<'token-market-page', '/TokenMarketPage', Record<never, never>, Record<never, never>>,
    'token-meta-page': RouteRecordInfo<'token-meta-page', '/TokenMetaPage', Record<never, never>, Record<never, never>>,
    'token-page': RouteRecordInfo<'token-page', '/TokenPage', Record<never, never>, Record<never, never>>,
    'token-page-backup': RouteRecordInfo<'token-page-backup', '/TokenPage-backup', Record<never, never>, Record<never, never>>,
    'token-volume-page': RouteRecordInfo<'token-volume-page', '/TokenVolumePage', Record<never, never>, Record<never, never>>,
    'volume-page': RouteRecordInfo<'volume-page', '/volume-page', Record<never, never>, Record<never, never>>,
  }
}
